# Generated by Django 2.1.5 on 2019-09-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190906_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.CharField(default='', max_length=150),
        ),
    ]
